dataset: ehrsql
db_id: eicu
test_data_path: dataset/ehrsql/eicu/valid.json
use_para: true
exp_name : eval_t5_ehrsql_eicu_natural_lr0.001_best__eicu_natural_valid

mode: eval
load_model_path: outputs/t5_ehrsql_eicu_natural_lr0.001/checkpoint_best.pth.tar
eval_batch_size: 8

tables_path: 
add_schema: false
add_column_type: false