dataset: ehrsql
db_id: eicu
test_data_path: dataset/ehrsql/eicu/valid.json
use_para: true
exp_name : eval_t5_ehrsql_eicu_natural_lr0.001_schema_best__eicu_natural_valid

mode: eval
load_model_path: outputs/t5_ehrsql_eicu_natural_lr0.001_schema/checkpoint_best.pth.tar
eval_batch_size: 8

tables_path: dataset/ehrsql/tables.json
add_schema: true
add_column_type: false
shuffle_schema: false