dataset: ehrsql
db_id: eicu
train_data_path : dataset/ehrsql/eicu/train.json
valid_data_path : dataset/ehrsql/eicu/valid.json

exp_name : t5_ehrsql_eicu_natural_lr0.001
use_para: true
mode: train
load_model_path: 
train_batch_size: 4
eval_batch_size: 8
lr: 0.001
accumulation_steps: 8
total_step: 100000

tables_path: 
add_schema: false
add_column_type: false

# use_wandb: true
# wandb_project: ehr-semantic-parsing
