dataset: ehrsql
db_id: mimic_iii
train_data_path : dataset/ehrsql/mimic_iii/train.json
valid_data_path : dataset/ehrsql/mimic_iii/valid.json

exp_name : t5_ehrsql_mimic3_natural_lr0.001_schema
use_para: true
mode: train
load_model_path: 
train_batch_size: 4
eval_batch_size: 8
lr: 0.001
accumulation_steps: 8
total_step: 100000

tables_path: dataset/ehrsql/tables.json
add_schema: true
add_column_type: false
shuffle_schema: false

# use_wandb: true
# wandb_project: ehr-semantic-parsing
